DROP SCHEMA IF EXISTS FREERIDER_DB;
CREATE SCHEMA IF NOT EXISTS FREERIDER_DB;
USE FREERIDER_DB;

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
  `ID` int NOT NULL,
  `NAME` varchar(60) DEFAULT NULL,
  `CONTACT` varchar(60) DEFAULT NULL,
  `STATUS` enum('Active','InRegistration','Terminated') DEFAULT NULL,

  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS VEHICLE;
CREATE TABLE VEHICLE (
  `ID` int NOT NULL,
  `MAKE` varchar(60) DEFAULT NULL,
  `MODEL` varchar(60) DEFAULT NULL,
  `SEATS` int DEFAULT '4',
  `CATEGORY` enum('Sedan','SUV','Convertible','Van','Bike') DEFAULT NULL,
  `POWER` enum('Gasoline','Diesel','Electric','Hybrid','Hydrogen') DEFAULT NULL,
  `STATUS` enum('Active','Serviced','Terminated') DEFAULT NULL,

  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS RESERVATION;
CREATE TABLE RESERVATION (
  `ID` int NOT NULL,
  `CUSTOMER_ID` int NOT NULL,
  `VEHICLE_ID` int NOT NULL,
  `BEGIN` datetime DEFAULT NULL,
  `END` datetime DEFAULT NULL,
  `PICKUP` varchar(48) DEFAULT NULL,
  `DROPOFF` varchar(48) DEFAULT NULL,
  `STATUS` enum('Inquired','InquiryConfirmed','Booked','Cancelled') DEFAULT NULL,

  PRIMARY KEY (ID),
  KEY IDX_CUSTOMER_ID (CUSTOMER_ID),
  KEY IDX_VEHICLE_ID (VEHICLE_ID),
  CONSTRAINT CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
  CONSTRAINT VEHICLE_ID FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE (ID)
);
